# Generated by Django 2.2.1 on 2019-05-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
    ]
