# Generated by Django 2.2.1 on 2019-06-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
