# Generated by Django 2.2.1 on 2019-06-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20190603_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
